// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfL9SEWxpe8XXrJVbduuG6XgcWk1K7i2c',
    appId: '1:1091669817384:web:02998adbc67c7b41df1d1d',
    messagingSenderId: '1091669817384',
    projectId: 'civic-84e44',
    authDomain: 'civic-84e44.firebaseapp.com',
    storageBucket: 'civic-84e44.firebasestorage.app',
    measurementId: 'G-73P1YC7WEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNVkZeiYqexowjIyE8RUHiBDZLwB7rEKA',
    appId: '1:1091669817384:android:abe313bcc4859b6edf1d1d',
    messagingSenderId: '1091669817384',
    projectId: 'civic-84e44',
    storageBucket: 'civic-84e44.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfL9SEWxpe8XXrJVbduuG6XgcWk1K7i2c',
    appId: '1:1091669817384:web:0109b9b573acfd32df1d1d',
    messagingSenderId: '1091669817384',
    projectId: 'civic-84e44',
    authDomain: 'civic-84e44.firebaseapp.com',
    storageBucket: 'civic-84e44.firebasestorage.app',
    measurementId: 'G-P1TY0XSNRZ',
  );
}
